### PR TITLE
Assembly - Chapter

### PR DESCRIPTION
**Pull request by gadilashashank**
The title says all. Also I was not able to find an exact date hence the name does not match the format

### CODE REVIEW

**Comment by gadilashashank** [comment]
@FilipeRamalho given the scope of the project as a read for people who do not "program" I do not think adding too many of the "technical stuffs" would in anyway interest a reader hence I've kept the content short, brief and crisp. 
But then if @ODXT decides to include more of the "technical stuffs" then I can gladly add more content.

**Comment by FilipeRamalho** [comment]
@gadilashashank I don't the technical background, but still there are more things to say about Assembly.

**Comment by ODXT** [comment]
As @FilipeRamalho says, we had a few structural changes (Recently). Please take your time to review. If you have any questions, please let me know.

**Comment by gadilashashank** [comment]
Yup I'll do the changes accordingly and come back on the PR

**Comment by gadilashashank** [comment]
Some errors are left over. I'll fix them in some time

**Comment by gadilashashank** [comment]
@devRant-Squad/editors request review.

**Comment by Skayo** [comment]
I really like the structure of this chapter. Maybe we should standardize it?

**Comment by FilipeRamalho** [comment]
Before the grammar has to be checked, I think there some grammar and capitalization errors

**Comment by gadilashashank** [comment]
I'll proofread once again.

**Comment by FilipeRamalho** [comment]
3rd Person review is required as I and the write can't agree on certain Things. The 3rd Person should read through everything and correct everything wrong.

**Comment by gadilashashank** [comment]
I've tried to include majority changes as specified by @FilipeRamalho and tried to add upon some changes suggested with the intent of not discarding them completely. But one block that I wish were not deleted is the one in the chapter "What it solves" (what_it_solves.md) where there was a block code in binary which was slightly altered to give the reader the feel of debugging in binary. I think letting it remain is a good idea and it reinforces ideas mentioned in the same section and the subsequent ones.

**Comment by FilipeRamalho** [comment]
I would except review only in the following week, could you till then clean up the commit tree, if you Need help with that say it and I clean it up, but keep the current stand of changes.

**Comment by gadilashashank** [comment]
@FilipeRamalho help with cleaning the tree. I did some random stuff that did not help

**Comment by FilipeRamalho** [comment]
The commit tree has been cleaned

**Comment by FilipeRamalho** [comment]
The commit tree is again huge. I will clean it again, please delete your local repo and then make a git pull.

**Comment by gadilashashank** [comment]
@FilipeRamalho could you teach me? I don't want you to do this every time...

**Comment by FilipeRamalho** [comment]
Did you delete the repo ?

**Comment by gadilashashank** [comment]
Closing this

**Pull request closed without merging**
