### PR TITLE
Added Icons in SVG & PNG

### PR DESCRIPTION
**Pull request by Parou**
Added current logos of the languages for later use in the chapters.

### CODE REVIEW

**Comment by Parou** [comment]
Oh, by the way: Is it okay that the icon folder is in /book/? I don't know how if that would make any problems and just thought that's the right folder for it.

**Comment by ODXT** [comment]
It sounds like a logical place. Test it out.

**Comment by Parou** [comment]
So... Am I allowed to just merge it..?

**Comment by Skayo** [comment]
Sure!

**Pull request merged**
